### ISSUE TITLE
ImGui Support

### ISSUE THREAD

**Issue by kassane** [kassane/sokol-d#10]
There are some Sokol examples to be ported that use ImGui.

Since only `build.zig` is available, zig-pkg will be used to download D packages.

https://github.com/kassane/sokol-d/blob/43d371b48e0a2ca951aa44234be8a9cbe9179e6b/build.zig.zon#L4-L10

### D binding
- https://github.com/BindBC/bindbc-imgui
- https://github.com/BindBC/bindbc-imgui/issues/2

# References
- https://github.com/floooh/sokol-zig/issues/29
- https://github.com/floooh/sokol-rust/issues/19
- https://github.com/floooh/sokol/blob/master/util/sokol_imgui.h

**Comment by floooh** [comment]
Imgui support in the bindings is currently a bit messy. sokol_imgui.h currently isn't included in the "original" bindings (Zig, Nim, Odin), but was only added by the contributed Rust bindings (but went stale there).

One reason (which tbh doesn't make a lot of sense) was that I didn't want to have any sort of external dependency in the bindings, e.g. there couldn't be an imgui example (such an example would need to live in a separate repo). But this also means that any problems in the sokol_imgui.h bindings wouldn't be caught by running the tests (since those just compile the included samples).

I guess it does make sense to include sokol_imgui.h in all bindings, even without an integrated sample.

Just some sort of braindump from my side ;)

**Comment by kassane** [comment]
After rebasing the project with wasm support and some fixes.
The ImGui library built by zig gives an error about not having found 'assert.h' which is only needed by ImGui.

I also tried to use `IM_ASSERT` macro define to replace C assert, but it gives several errors in the API.
I don't know how this custom assert works since I haven't seen it in any examples.

``` bash
install
+- emcc
   +- mrt
      +- zig build-lib sokol ReleaseSmall wasm32-emscripten
         +- zig build-lib cimgui ReleaseSmall wasm32-emscripten 6 errors
/home/runner/.cache/zig/p/12202af0db41b79a4c7904950269b5e33b7d48f50aae042e334cb8d717a5a2caf48d/imgui.h:84:10: error: 'assert.h' file not found
/home/runner/.cache/zig/p/1220e6183fb9559dbfafe58d7fab20f1c330bee32342205815aa10553134ff9f9302/cimgui.cpp:13:10: note: in file included from /home/runner/.cache/zig/p/1220e6183fb9559dbfafe58d7fab20f1c330bee32342205815aa10553134ff9f9302/cimgui.cpp:13:
/home/runner/.cache/zig/p/12202af0db41b79a4c7904950269b5e33b7d48f50aae042e334cb8d717a5a2caf48d/imgui.h:84:10: error: 'assert.h' file not found
/home/runner/.cache/zig/p/12202af0db41b79a4c7904950269b5e33b7d48f50aae042e334cb8d717a5a2caf48d/imgui_demo.cpp:96:10: note: in file included from /home/runner/.cache/zig/p/12202af0db41b79a4c7904950269b5e33b7d48f50aae042e334cb8d717a5a2caf48d/imgui_demo.cpp:96:
/home/runner/.cache/zig/p/12202af0db41b79a4c7904950269b5e33b7d48f50aae042e334cb8d717a5a2caf48d/imgui.h:84:10: error: 'assert.h' file not found
/home/runner/.cache/zig/p/12202af0db41b79a4c7904950269b5e33b7d48f50aae042e334cb8d717a5a2caf48d/imgui_draw.cpp:33:10: note: in file included from /home/runner/.cache/zig/p/12202af0db41b79a4c7904950269b5e33b7d48f50aae042e334cb8d717a5a2caf48d/imgui_draw.cpp:33:
[...]
````

**Comment by kassane** [comment]
updated branch e new issue detected on imgui:
```bash
 zig build run-imgui
/home/kassane/sokol-d/src/examples/imgui.d(25,14): `state` is thread local
imgui: /home/kassane/.cache/zig/p/12202af0db41b79a4c7904950269b5e33b7d48f50aae042e334cb8d717a5a2caf48d/imgui.cpp:9526: void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `(g.FrameCount == 0 || g.FrameCountEnded == g.FrameCount) && "Forgot to call Render() or EndFrame() at the end of the previous frame?"' failed.
run-imgui
└─ run /home/kassane/sokol-d/zig-out/bin/imgui failure
```

**Comment by floooh** [comment]
Btw, I tinkered a bit with imgui-support in the Rust bindings:

https://github.com/floooh/sokol/commit/b728ee66d1d8a83247bdde75aacb299aee294475

Note how I'm adding the sokol_imgui.h header only to the Rust bindings generation.

I ignored the `simgui_add_key_event` function because the function signature is not yet supported by the bindings generator and it's a fairly esoteric function.

I also had to remove the sokol_gfx_imgui.h bindings, because this has a union in the public API, which isn't supported either.

Ultimately I didn't get it working, because the Rust imgui bindings (`imgui_sys`) are stuck on an older ImGui version than the sokol_imgui.h header doesn't support anymore.

I'm now also slowly seeing the light at the end of the rabbit hole I'm currently in (https://github.com/floooh/sokol/pull/985) after that hopefully have a bit of time for looking into the bindings before the next 'big thing' (storage buffers).

**Comment by floooh** [comment]
Btw 2: I have removed the imgui-stuff in the Rust bindings for now. There was a cimgui git submodule in the examples which caused trouble in the GH Actions jobs (artifacts with git submodules included fail to download in a Windows job). I didn't feel like investigating this and delay the render-pass-cleanup merge. If we add sokol_imgui.h bindings and examples we should do it in a way that works for all bindings.

**Comment by kassane** [comment]
**WiP** - some fixes
![image](https://github.com/kassane/sokol-d/assets/6756180/6e94ab23-85fd-4ca9-b8ed-e132b9f7c6c5)

**Comment by kassane** [comment]
> The ImGui library built by zig gives an error about not having found 'assert.h' which is only needed by ImGui.

Which cflag/cdefine solves `assert.h` in wasm?

**Comment by kassane** [comment]
new commit: https://github.com/kassane/sokol-d/commit/9198de3ea7ad7cb35f1674619eac9708e11be6dd broken `imgui` branch

**Comment by kassane** [comment]
see:
- https://github.com/floooh/sokol-zig/pull/69

**Comment by floooh** [comment]
Btw the tricky part is to inject a cimgui header search path into the sokol C libary build (without adding a dependency to cimgui/Dear ImGui to the sokol-zig package. So the other important half is here in the example project:

https://github.com/floooh/sokol-zig-imgui-sample/blob/main/build.zig

**Comment by kassane** [comment]
> Btw the tricky part is to inject a cimgui header search path into the sokol C libary build without adding a dependency to cimgui/Dear ImGui to the sokol-zig package. So the other important half is here in the example project:
> 
> https://github.com/floooh/sokol-zig-imgui-sample/blob/main/build.zig

I see. However, the writefiles stepwait breaks my build.
I tried adapting buildimgui and later copying its configuration and still got the same step error.

**Comment by kassane** [comment]
How to skip IMGUI assert on wasm target?

```bash
/home/kassane/.cache/zig/p/122072b125179c7cbdbbee8fa81d22a1050a950ad61cfeefee8dc0dca5423b5d05b9/imgui.h:88:10: error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~~
/home/kassane/.cache/zig/p/122072b125179c7cbdbbee8fa81d22a1050a950ad61cfeefee8dc0dca5423b5d05b9/imgui_tables.cpp:198:10: note: in file included from /home/kassane/.cache/zig/p/122072b125179c7cbdbbee8fa81d22a1050a950ad61cfeefee8dc0dca5423b5d05b9/imgui_tables.cpp:198:
#include "imgui.h"
```
