### ISSUE TITLE
Make Zig 0.14.0 build-system great again

### ISSUE THREAD

**Issue by kassane** [kassane/sokol-d#44]
Currently, with the latest commit by @floooh, it is compatible with 0.13.0 or older 0.14.0-dev builds.

##### References

- #43
- https://github.com/ziglang/zig/pull/20388#issuecomment-2550174900

**Comment by floooh** [comment]
Btw, and somewhat unrelated: I have switched the `setup-zig` GH Actions to `mlugg/setup-zig` in the sokol repository: 

https://github.com/floooh/sokol/commit/5ff951779fad98d1aab785a669cd7b40a3b1873f

Since mlugg seems to the 'build system guy' on the Zig project I guess this is as close to an official setup action as we can get outside of a `ziglang/setup-zig` action ;)

If this runs stable and fast we should probably switch the sokol-d script too.

**Comment by kassane** [comment]
> Btw, and somewhat unrelated: I have switched the `setup-zig` GH Actions to `mlugg/setup-zig` in the sokol repository:

I also use it on some repositories. Sometimes the delay is uncomfortable on some mirrors.
However, if we want to maintain the same standard, I don't see any problem replace to `mlugg/setup-zig`.

I'll also try resuming the `pacman.d` [CI: `mlugg/setup-zig`] build (I'd put it aside for lack of time).
